name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy to FTP
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
            -e "set sftp:server=${{ secrets.FTP_SERVER }}; \
                 set sftp:passive-mode=true; \
                 set ftps-wrapper-command=openssl s_client -connect ${{ secrets.FTP_SERVER }}:21 -quiet; \
                 open ${{ secrets.FTP_SERVER }}; \
                 cd ${{ secrets.FTP_DIR }}; \
                 put -c -r ./*; \
                 bye" <<EOF
          set ssl:verify-certificate off
          set ftps-wrapper-command openssl s_client -connect ${{ secrets.FTP_SERVER }}:21 -quiet
          open ${{ secrets.FTP_SERVER }}
          cd ${{ secrets.FTP_DIR }}
          put -c -r ./*
          bye
          EOF
